project:
  type: book

book:
  title: "Memoir"
  author: "Jack Huber"
  date: "10/4/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

